inputs_def:
  - handle: pdf_path
    description: "%path-to-the-input-pdf-file-to-be-converted-the-file-must-be-a-va%"
    json_schema:
      type: string
      ui:widget: file
    nullable: false

  - group: Optional
    collapsed: false

  - handle: output_path
    description: "%destination-path-where-the-converted-epub-file-will-be-saved-if%"
    json_schema:
      type: string
      ui:widget: save
      ui:options:
        filters:
          - name: EPUB
            extensions:
              - epub
        excludeAll: true
    value:
    nullable: true

  - handle: includes_footnotes
    description: "%controls-whether-footnotes-in-the-pdf-document-should-be-preserv%"
    json_schema:
      type: boolean
    value:
    nullable: true

  - handle: ocr_model
    description: "%specifies-the-ocr-optical-character-recognition-model-size-to-us%"
    json_schema:
      type: string
      enum:
        - gundam
        - large
        - base
        - small
        - tiny
    value:
    nullable: true

  - handle: book_title
    description: "%sets-the-title-metadata-for-the-generated-epub-file-this-title-w%"
    json_schema:
      type: string
    value:
    nullable: true

  - handle: book_authors
    description: "%specifies-the-author-s-metadata-for-the-generated-epub-file-for%"
    json_schema:
      type: string
    value:
    nullable: true

  - handle: table_render
    description: "%determines-how-tables-in-the-pdf-should-be-rendered-in-the-epub%"
    json_schema:
      type: string
      enum:
        - HTML
        - CLIPPING
    value:
    nullable: true

  - handle: latex_render
    description: "%controls-how-latex-mathematical-formulas-and-equations-should-be%"
    json_schema:
      type: string
      enum:
        - MathML
        - LaTeX
    value:
    nullable: true

  - handle: generate_plot
    description: "%enables-or-disables-the-generation-of-analysis-visualizations-du%"
    json_schema:
      type: boolean
    value:
    nullable: true

outputs_def:
  - handle: epub_path
    description: "%absolute-file-path-to-the-successfully-generated-epub-file-this%"
    json_schema:
      type: string

executor:
  name: python
  options:
    entry: __init__.py
    spawn: false

title: "%pdf-to-epub%"
icon: ":carbon:document-pdf:"
description: "%convert-pdf-documents-to-epub-electronic-publication-format-usin%"
